app2/urls.py
from django.urls import path
from app2.views import *
app_name='login'
urlpatterns=[
    path('login/',login,name='login')
]

webapp1/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import *
import app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',register,name='register'),
    path('app2/',include('app2.urls'))
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def register(request):
    return render(request,'register.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def login(request):
    return render(request,'login.html')

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
    form{
      background:linear-gradient(198deg,rgb(241, 241, 76),rgb(116, 193, 116));
      margin: 0px 20%;
      padding: 5px 0px;
      border-radius: 20px;
    }
    body{
      margin: 150px;
      background:linear-gradient(233deg,lightgreen,rgb(148, 199, 148));
      height: 430px;
    }
    input{
      padding: 2px 10px;
    }
    a{
      text-decoration: none;
    color: rgb(39, 34, 34);
    }
  </style>
</head>
<body>
  <center>
    <form action="">
      
        <h1><span>LOGIN</span></h1>
        <div>
          <div>
            <input type="email" placeholder="EMAIL ID">
          </div>
          <br>
          <div>
            <input type="password" placeholder="PASSWORD">
          </div>
          <br>

          <div>
            <button class="Lbutton"> <a href="" >LOGIN</a> </button>
          </div>
          <br>
          <div>
            <a href="PASSWORD" target="password" target="email">FORGOT EMAIL/PASSWORD</a>
          </div>
          <br>
        </div>
    </form>
  </center> 
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  
  <style>
    .form{
    border: 1px solid brown;
    margin: 0px 30%;
    background:linear-gradient(129deg,brown,red);
    border-radius: 30px;
    padding-top: 20px;
  
   }
   form{
    box-shadow: 0 0 10px rgba(200, 75, 75, 0.6);
    -moz-box-shadow: 0 0 10px rgba(200, 75, 75, 0.6);
    -webkit-box-shadow: 0 0 10px rgba(200, 75, 75, 0.6);
    -o-box-shadow: 0 0 10px rgba(200, 75, 75, 0.6);
   }
   body{
    margin-top: 170px;
   }
   a{
    text-decoration: none;
   }
   h1{
    background:linear-gradient(129deg,brown,red);
    margin: 0 25%;
    border-radius: 20px;
   }
   h1:hover{
       color: rgb(0, 0, 0);
       background:linear-gradient(129deg,rgb(203, 160, 160),rgb(219, 133, 133));
   }
   .Rbutton{
    background:linear-gradient(129deg,rgba(206, 204, 204, 0.6),rgba(206, 204, 204, 0.6));
    box-shadow: 0 0 20px rgba(206, 204, 204, 0.8);
    -moz-box-shadow: 0 0 20px  rgba(206, 204, 204, 0.8);
    -webkit-box-shadow: 0 0 20px  rgba(206, 204, 204, 0.8);
    -o-box-shadow: 0 0 20px  rgba(206, 204, 204, 0.8);
    padding: 4px 15px;
    border-radius: 20px;
    
   }
   input{
    border-radius: 20px;
   }
   body{
    background-color: brown;
    background-repeat: cover;
   }
  </style>
</head>
<body>
  <center>
    <form action="" class="form">
      
        <h1><span>REGISTER-FORM</span></h1>
        <br>
        <h4>if u already have an account <a href="{% url 'login:login' %}">signin/login</a> </h4>
        <div>
          <div>
            <input type="text" placeholder="FIRST-NAME" name="FIRST-NAME" required>
          </div>
          <br>
          <div>
            <input type="text" placeholder="LAST-NAME" name="LAST-NAME" required>
          </div>
          <br>
          <div>
            <input type="email" placeholder="EMAIL" name="EMAIL" required>
          </div>
          <br>
          <div>
            <input type="password" placeholder="PASSWORD" name="PASSWORD" required>
          </div>
          <br>
          <div>
            <input type="password" placeholder="CONFIRM-PASSWORD" name="C PASSWORD" required>
          </div><br>
          <div>
            <input type="checkbox"> <span>I Accept <a href="">Terms of Use?</a></span>
          </div><br>
          <div>
            <button class="Rbutton"> <a href="{% url 'login:login' %}" style="color: rgb(23, 34, 44);" >REGISTER NOW</a> </button>
          </div><br>
        </div>
    </form>
  </center> 
</body>
</html>